version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/base:2024.01

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: echo "build"

  test:
    executor: my-executor
    steps:
      - checkout
      - run: echo "test"

  deploy:
    executor: my-executor
    steps:
      - checkout

      # Ensure that deploy.sh exists and has execute permission
      - run:
          name: Check deploy.sh file
          command: |
            ls -l .circleci/deploy.sh
            chmod +x .circleci/deploy.sh

      # Debugger
      - run:
          name: Deploy to Website via SSH
          command: |
            set -x
            .circleci/deploy.sh
            set +x

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
