version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/python:3.8"
    
    steps:
      - checkout
      # Add more steps as needed for your build process

workflows:
  version: 2
  build:
    jobs:
      - build

