version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/base:2024.01

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: echo "build"

  test:
    executor: my-executor
    steps:
      - checkout
      - run: echo "test"

  deploy:
    executor: my-executor
    steps:
      - checkout

      # Ensure that deploy.sh exists and has execute permission
      - run:
          name: Check deploy.sh file
          command: |
            ls -l deploy.sh
            chmod +x deploy.sh

      # Debugger
      - run:
          name: Debug
          command: ls -l

      # Add host key to known hosts
      - run:
          name: Add host key to known hosts
          command: echo "u3aonline.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICoVOPK9DxxLsRQQXj6lL68EDOMXNMOTwSlYGglz7DRM" >> ~/.ssh/known_hosts

      # SSH into your server and execute deployment commands
      - run:
          name: Deploy to Website via SSH
          command: |
            ssh -i .circleci/LightsailDefaultKey-ap-southeast-2.pem bitnami@u3aonline.com "cd /opt/bitnami/apache2/htdocs/ && ./deploy.sh"
          # Replace "bitnami@u3aonline.com", "/opt/bitnami/apache2/htdocs/", and "./deploy.sh" with your actual values.

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
