version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/base:2024.01

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: echo "build"

  test:
    executor: my-executor
    steps:
      - checkout
      - run: echo "test"

  deploy:
    executor: my-executor
    steps:
      - checkout

      # Ensure that deploy.sh exists and has execute permission
      - run:
          name: Check deploy.sh file
          command: |
            ls -l deploy.sh
            chmod +x deploy.sh

      # Debugger
      - run:
          name: Debug
          command: ls -l

      # Create .ssh directory with correct permissions
      - run:
          name: Create .ssh directory
          command: mkdir -p ~/.ssh && chmod 700 ~/.ssh

      # Update the known_hosts file with the host key fingerprint
      - run:
          name: Update known_hosts file
          command: |
            ssh-keyscan -t ed25519 u3aonline.com >> ~/.ssh/known_hosts

      # SSH into your server and execute deployment commands
      - run:
          name: Deploy to Website via SSH
          command: |
            ssh -i .circleci/LightsailDefaultKey-ap-southeast-2.pem bitnami@u3aonline.com "cd /opt/bitnami/apache2/htdocs/ && ./deploy.sh"
          

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
