version: 2.1
# https://circleci.com/docs/sample-config/

executors: # Define an executor
  my-executor:
    docker:
      - image: cimg/base:2024.01

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: echo "build"

  test:
    executor: my-executor
    steps:
      - checkout
      - run: echo "test"

  deploy:
    executor: my-executor
    steps:
      - checkout
      # SSH key scan
      - run:
          name: Add SSH key to known_hosts
          command: ssh-keyscan -H u3aonline.com >> ~/.ssh/known_hosts

      # Debugger
      - run:
          name: Debug
          command: ls -l

      # SSH into your server and execute deployment commands
      - run:
          name: Deploy to Website via SSH
          command: |
            ssh -i .circleci/LightsailDefaultKey-ap-southeast-2.pem bitnami@u3aonline.com "cd /opt/bitnami/apache2/htdocs/ && ./deploy.sh"
          # Replace "bitnami@u3aonline.com", "/opt/bitnami/apache2/htdocs/", and "./deploy.sh" with your actual values.
  

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
