version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/base:2024.01

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: echo "build"

  test:
    executor: my-executor
    steps:
      - checkout
      - run: echo "test"

  deploy:
    executor: my-executor
    steps:
      - checkout

      # Ensure that deploy.sh exists and has execute permission
      - run:
          name: Check deploy.sh file
          command: |
            ls -l deploy.sh
            chmod +x deploy.sh

      # Debugger
      - run:
          name: Deploy to Website via SSH (Debug)
          command: |
            set -x
            ssh -o StrictHostKeyChecking=no -i .circleci/LightsailDefaultKey-ap-southeast-2.pem bitnami@u3aonline.com "cd /opt/bitnami/apache2/htdocs/ && ./deploy.sh"
            set +x

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
