version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/base:2024.01

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: echo "build"

  test:
    executor: my-executor
    steps:
      - checkout
      - run: echo "test"

  deploy:
    executor: my-executor
    steps:
      - checkout

      # Ensure that deploy.bat exists and has execute permission
      - run:
          name: Check deploy.bat file
          command: |
            if not exist .circleci\deploy.bat (
              echo "deploy.bat does not exist"
              exit 1
            )

      # Execute deploy.bat
      - run:
          name: Deploy to Website via SSH
          command: .circleci\deploy.bat

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
