name: Deploy WordPress Theme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy Theme to WordPress
        run: |
          scp -r path/to/your/wordpress/theme user@your-server-ip:/path/to/wordpress/wp-content/themes
